// GENERATED by scripts/gen-zod.mjs from spec/protect-7.1.87.openapi.json. Do not edit by hand.
// Regenerate with: npm run gen:zod
/* eslint-disable */
import { z } from 'zod'

export const activationDelaySchema = z.union([z.literal(0), z.literal(60000), z.literal(300000), z.literal(600000)])
export type ActivationDelay = z.infer<typeof activationDelaySchema>

export const activePatrolSlotSchema = z.number()
export type ActivePatrolSlot = z.infer<typeof activePatrolSlotSchema>

export const activePatrolSlotStringSchema = z.string()
export type ActivePatrolSlotString = z.infer<typeof activePatrolSlotStringSchema>

export const aiportModelKeySchema = z.literal("aiport")
export type AiportModelKey = z.infer<typeof aiportModelKeySchema>

export const aiprocessorModelKeySchema = z.literal("aiprocessor")
export type AiprocessorModelKey = z.infer<typeof aiprocessorModelKeySchema>

export const alarmHubStatusSchema = z.looseObject({
  "armed": z.enum(["on", "off"]),
  "battery": z.looseObject({
  "charging": z.enum(["on", "off"]).optional(),
  "connection": z.enum(["connected", "disconnected"]).optional(),
  "voltage": z.number().optional(),
  "batteryStatus": z.enum(["ok", "low", "critical"]).optional(),
}).optional(),
  "buckboost": z.enum(["on", "off"]),
  "connector": z.looseObject({
  "emergency": z.looseObject({
  "+": z.enum(["connected", "disconnected"]),
  "-": z.enum(["connected", "disconnected"]),
}).optional(),
  "12v": z.record(z.string(), z.looseObject({
  "+": z.enum(["connected", "disconnected"]),
  "-": z.enum(["connected", "disconnected"]),
})).optional(),
  "relay": z.record(z.string(), z.looseObject({
  "com": z.enum(["connected", "disconnected"]),
  "nc": z.enum(["connected", "disconnected"]),
  "no": z.enum(["connected", "disconnected"]),
})).optional(),
  "tb": z.record(z.string(), z.looseObject({
  "+": z.enum(["connected", "disconnected"]),
  "-": z.enum(["connected", "disconnected"]),
})).optional(),
  "battery": z.enum(["connected", "disconnected"]).optional(),
  "poeout": z.enum(["connected", "disconnected"]).optional(),
}).optional(),
  "cover": z.looseObject({
  "distance": z.number().int().optional(),
  "status": z.enum(["open", "close"]).optional(),
}).optional(),
  "currentMeterChannelStatus": z.record(z.string(), z.looseObject({
  "criticalAlarm": z.enum(["normal", "alert"]),
  "criticalThreshold": z.number(),
  "value": z.number(),
  "warningAlarm": z.enum(["normal", "alert"]),
  "warningThreshold": z.number(),
})),
  "currentMeterStatus": z.record(z.string(), z.looseObject({
  "critical": z.enum(["normal", "alert"]),
  "efuse": z.enum(["normal", "warning", "fault"]),
  "enable": z.enum(["on", "off"]),
  "powerValid": z.enum(["normal", "alert"]),
  "timingControl": z.enum(["normal", "alert"]),
  "warning": z.enum(["normal", "alert"]),
})),
  "inputPower": z.looseObject({
  "bt": z.enum(["low", "high"]).optional(),
  "typ1": z.enum(["low", "high"]).optional(),
  "typ2": z.enum(["low", "high"]).optional(),
}).optional(),
  "poeout": z.looseObject({
  "connection": z.enum(["connected", "disconnected"]).optional(),
  "powerSupply": z.enum(["on", "off"]).optional(),
}).optional(),
  "powerMeter": z.record(z.string(), z.looseObject({
  "alarm": z.enum(["normal", "alert"]),
  "current": z.number(),
  "efuse": z.enum(["normal", "warning", "fault"]),
  "enable": z.enum(["on", "off"]),
  "power": z.number(),
  "powerThreshold": z.number(),
  "voltage": z.number(),
})),
  "output": z.record(z.string(), z.looseObject({
  "enable": z.enum(["on", "off"]),
  "active": z.enum(["on", "off"]),
  "status": z.enum(["wet", "dry"]),
  "delay": z.number().int().optional(),
  "duration": z.number().int().optional(),
  "name": z.string().optional(),
})),
  "input": z.record(z.string(), z.looseObject({
  "enable": z.enum(["on", "off"]),
  "type": z.union([z.literal("no"), z.literal("nc")]),
  "eolr": z.number().int().min(0).max(2),
  "resistor": z.number().min(0).max(10),
  "status": z.enum(["normal", "alarm", "fault", "short", "cut"]),
  "trigger": z.number().int(),
  "name": z.string().optional(),
  "inputType": z.enum(["MOTION", "ENTRY", "SMOKE", "GLASS_BREAK", "EMERGENCY_BUTTON"]).optional(),
  "allowedArmingProfiles": z.array(z.string()).optional(),
  "triggerWhenDisarmed": z.enum(["on", "off"]).optional(),
  "triggerOnCurrentArmingProfile": z.enum(["on", "off"]).optional(),
  "lastTriggeredAt": z.number().nullable().optional(),
  "cameraId": z.string().nullable().optional(),
  "powerReset": z.boolean().optional(),
})),
  "inputTerminalStatus": z.record(z.string(), z.looseObject({
  "plusPinStatus": z.enum(["disabled", "idle", "not-connected", "tamper", "triggered", "cut", "short"]),
  "minusPinStatus": z.enum(["disabled", "idle", "not-connected", "tamper", "triggered", "cut", "short"]),
  "terminalStatus": z.enum(["disabled", "idle", "not-connected", "tamper", "triggered", "cut", "short", "partially-connected"]),
  "idleSubState": z.enum(["open", "closed"]).optional(),
})).optional(),
  "outputTerminalStatus": z.record(z.string(), z.looseObject({
  "pins": z.looseObject({
  "no": z.enum(["disabled", "idle", "not-connected", "tamper", "triggered", "cut", "short"]),
  "com": z.enum(["disabled", "idle", "not-connected", "tamper", "triggered", "cut", "short"]),
  "nc": z.enum(["disabled", "idle", "not-connected", "tamper", "triggered", "cut", "short"]),
}),
  "statusLabel": z.enum(["disabled", "off", "active"]),
  "mode": z.enum(["dry-contact", "powered-12v"]),
  "efuseAlert": z.enum(["none", "high-current", "over-current"]),
  "wiredPins": z.array(z.enum(["+", "-", "nc", "no", "com"])),
})).optional(),
  "emergencyTerminalStatus": z.looseObject({
  "plusPinStatus": z.enum(["disabled", "idle", "not-connected", "tamper", "triggered", "cut", "short"]),
  "minusPinStatus": z.enum(["disabled", "idle", "not-connected", "tamper", "triggered", "cut", "short"]),
  "terminalStatus": z.enum(["disabled", "idle", "not-connected", "tamper", "triggered", "cut", "short", "partially-connected"]),
  "idleSubState": z.enum(["open", "closed"]).optional(),
}).nullable().optional(),
  "auxiliaryPowerTerminalStatus": z.record(z.string(), z.looseObject({
  "plusPinStatus": z.enum(["disabled", "idle", "not-connected", "tamper", "triggered", "cut", "short"]),
  "minusPinStatus": z.enum(["disabled", "idle", "not-connected", "tamper", "triggered", "cut", "short"]),
  "status": z.enum(["not-connected", "partially-connected", "connected"]),
  "currentMa": z.number().optional(),
  "loadPercent": z.number().optional(),
})).optional(),
})
export type AlarmHubStatus = z.infer<typeof alarmHubStatusSchema>

export const alarmSettingsSchema = z.looseObject({
  "isEnabled": z.boolean().optional(),
})
export type AlarmSettings = z.infer<typeof alarmSettingsSchema>

export const alarmTriggerIdSchema = z.string()
export type AlarmTriggerId = z.infer<typeof alarmTriggerIdSchema>

export const armProfileIdSchema = z.string()
export type ArmProfileId = z.infer<typeof armProfileIdSchema>

export const armProfileNameSchema = z.string().min(1).max(255)
export type ArmProfileName = z.infer<typeof armProfileNameSchema>

export const armScheduleEndSchema = z.string()
export type ArmScheduleEnd = z.infer<typeof armScheduleEndSchema>

export const armScheduleStartSchema = z.string()
export type ArmScheduleStart = z.infer<typeof armScheduleStartSchema>

export const assetFileTypeSchema = z.literal("animations")
export type AssetFileType = z.infer<typeof assetFileTypeSchema>

export const audioTypesSchema = z.array(z.enum(["alrmSmoke", "alrmCmonx", "alrmSiren", "alrmBabyCry", "alrmSpeak", "alrmBark", "alrmBurglar", "alrmCarHorn", "alrmGlassBreak"]))
export type AudioTypes = z.infer<typeof audioTypesSchema>

export const automationIdSchema = z.string()
export type AutomationId = z.infer<typeof automationIdSchema>

export const batteryStatusSchema = z.looseObject({
  "percentage": z.number().nullable().optional(),
  "isLow": z.boolean().optional(),
})
export type BatteryStatus = z.infer<typeof batteryStatusSchema>

export const bridgeClientsSchema = z.array(z.string())
export type BridgeClients = z.infer<typeof bridgeClientsSchema>

export const bridgeIdSchema = z.string()
export type BridgeId = z.infer<typeof bridgeIdSchema>

export const bridgeMaxClientsSchema = z.number()
export type BridgeMaxClients = z.infer<typeof bridgeMaxClientsSchema>

export const bridgeModelKeySchema = z.literal("bridge")
export type BridgeModelKey = z.infer<typeof bridgeModelKeySchema>

export const bridgePlatformSchema = z.string().nullable()
export type BridgePlatform = z.infer<typeof bridgePlatformSchema>

export const cameraFeatureFlagsSchema = z.looseObject({
  "supportFullHdSnapshot": z.boolean(),
  "hasHdr": z.boolean(),
  "smartDetectTypes": z.array(z.enum(["person", "vehicle", "package", "licensePlate", "face", "animal"])),
  "smartDetectAudioTypes": z.array(z.enum(["alrmSmoke", "alrmCmonx", "alrmSiren", "alrmBabyCry", "alrmSpeak", "alrmBark", "alrmBurglar", "alrmCarHorn", "alrmGlassBreak"])),
  "videoModes": z.array(z.enum(["default", "highFps", "homekit", "sport", "slowShutter", "lprReflex", "lprNoneReflex"])),
  "hasMic": z.boolean(),
  "hasLedStatus": z.boolean(),
  "hasSpeaker": z.boolean(),
})
export type CameraFeatureFlags = z.infer<typeof cameraFeatureFlagsSchema>

export const cameraIdSchema = z.string()
export type CameraId = z.infer<typeof cameraIdSchema>

export const cameraModelKeySchema = z.literal("camera")
export type CameraModelKey = z.infer<typeof cameraModelKeySchema>

export const channelQualitySchema = z.enum(["high", "medium", "low", "package"])
export type ChannelQuality = z.infer<typeof channelQualitySchema>

export const chimeIdSchema = z.string()
export type ChimeId = z.infer<typeof chimeIdSchema>

export const chimeModelKeySchema = z.literal("chime")
export type ChimeModelKey = z.infer<typeof chimeModelKeySchema>

export const createdAtSchema = z.number()
export type CreatedAt = z.infer<typeof createdAtSchema>

// WARNING: the spec sets `additionalProperties: false` on this schema, so unlike
// every looseObject below it REJECTS unknown fields. A newer firmware adding a
// field here fails validation — consumers must degrade rather than throw.
export const createdRtspsStreamsSchema = z.strictObject({
  "high": z.url().optional(),
  "medium": z.url().optional(),
  "low": z.url().optional(),
  "package": z.url().optional(),
})
export type CreatedRtspsStreams = z.infer<typeof createdRtspsStreamsSchema>

export const deviceIdSchema = z.string()
export type DeviceId = z.infer<typeof deviceIdSchema>

export const deviceStateSchema = z.enum(["CONNECTED", "CONNECTING", "DISCONNECTED"])
export type DeviceState = z.infer<typeof deviceStateSchema>

export const doorbellSettingsSchema = z.looseObject({
  "defaultMessageText": z.string().optional(),
  "defaultMessageResetTimeoutMs": z.number().optional(),
  "customMessages": z.array(z.string()).optional(),
  "customImages": z.array(z.looseObject({
  "preview": z.string(),
  "sprite": z.string(),
})).optional(),
})
export type DoorbellSettings = z.infer<typeof doorbellSettingsSchema>

export const enableAtSchema = z.union([z.literal("fulltime"), z.literal("dark")])
export type EnableAt = z.infer<typeof enableAtSchema>

export const eventIdSchema = z.string()
export type EventId = z.infer<typeof eventIdSchema>

export const eventModelKeySchema = z.literal("event")
export type EventModelKey = z.infer<typeof eventModelKeySchema>

// WARNING: the spec sets `additionalProperties: false` on this schema, so unlike
// every looseObject below it REJECTS unknown fields. A newer firmware adding a
// field here fails validation — consumers must degrade rather than throw.
export const existingRtspsStreamsSchema = z.strictObject({
  "high": z.url().nullable().optional(),
  "medium": z.url().nullable().optional(),
  "low": z.url().nullable().optional(),
  "package": z.url().nullable().optional(),
})
export type ExistingRtspsStreams = z.infer<typeof existingRtspsStreamsSchema>

export const fileNameSchema = z.string()
export type FileName = z.infer<typeof fileNameSchema>

export const fileOriginalNameSchema = z.string()
export type FileOriginalName = z.infer<typeof fileOriginalNameSchema>

export const filePathSchema = z.string()
export type FilePath = z.infer<typeof filePathSchema>

export const fingerprintMetadataSchema = z.looseObject({
  "fingerprint": z.looseObject({
  "ulpId": z.string().nullable(),
}),
})
export type FingerprintMetadata = z.infer<typeof fingerprintMetadataSchema>

export const fobAwayStateSchema = z.enum(["ONLINE", "RECENTLY_SEEN", "NO_RECENT_HEARTBEAT", "DEVICE_LOST"])
export type FobAwayState = z.infer<typeof fobAwayStateSchema>

export const fobButtonLabelsSchema = z.enum(["securityActions", "positionHint"])
export type FobButtonLabels = z.infer<typeof fobButtonLabelsSchema>

export const fobButtonsSchema = z.array(z.enum(["function", "alarmHubButton", "arm", "disarm", "night", "panic", "left", "right", "input1", "input2"]))
export type FobButtons = z.infer<typeof fobButtonsSchema>

export const fobIdSchema = z.string()
export type FobId = z.infer<typeof fobIdSchema>

export const fobModelKeySchema = z.literal("fob")
export type FobModelKey = z.infer<typeof fobModelKeySchema>

export const forceHighQualitySchema = z.enum(["true", "false"])
export type ForceHighQuality = z.infer<typeof forceHighQualitySchema>

export const genericErrorSchema = z.looseObject({
  "error": z.string(),
  "name": z.string(),
  "cause": z.record(z.string(), z.unknown()).optional(),
})
export type GenericError = z.infer<typeof genericErrorSchema>

export const glassBreakSettingsSchema = z.looseObject({
  "isEnabled": z.boolean().optional(),
  "sensitivity": z.number().min(0).max(100).optional(),
  "sensitivityWhenArmed": z.number().min(0).max(100).optional(),
})
export type GlassBreakSettings = z.infer<typeof glassBreakSettingsSchema>

export const hasPackageCameraSchema = z.boolean()
export type HasPackageCamera = z.infer<typeof hasPackageCameraSchema>

export const hdrTypeSchema = z.enum(["auto", "on", "off"])
export type HdrType = z.infer<typeof hdrTypeSchema>

export const humiditySettingsSchema = z.looseObject({
  "isEnabled": z.boolean().optional(),
  "margin": z.number().optional(),
  "lowThreshold": z.number().min(1).max(99).nullable().optional(),
  "highThreshold": z.number().nullable().optional(),
})
export type HumiditySettings = z.infer<typeof humiditySettingsSchema>

export const idRequiredErrorSchema = z.looseObject({
  "error": z.string(),
  "name": z.string(),
  "cause": z.record(z.string(), z.unknown()).optional(),
})
export type IdRequiredError = z.infer<typeof idRequiredErrorSchema>

export const isDarkSchema = z.boolean()
export type IsDark = z.infer<typeof isDarkSchema>

export const isLightForceEnabledSchema = z.boolean()
export type IsLightForceEnabled = z.infer<typeof isLightForceEnabledSchema>

export const isLightOnSchema = z.boolean()
export type IsLightOn = z.infer<typeof isLightOnSchema>

export const isMicEnabledSchema = z.boolean()
export type IsMicEnabled = z.infer<typeof isMicEnabledSchema>

export const isPirMotionDetectedSchema = z.boolean()
export type IsPirMotionDetected = z.infer<typeof isPirMotionDetectedSchema>

export const lastMotionSchema = z.number().nullable()
export type LastMotion = z.infer<typeof lastMotionSchema>

export const lcdMessageSchema = z.union([z.looseObject({
  "type": z.literal("DO_NOT_DISTURB"),
  "resetAt": z.number().nullable().optional(),
}), z.looseObject({
  "type": z.literal("LEAVE_PACKAGE_AT_DOOR"),
  "resetAt": z.number().nullable().optional(),
}), z.looseObject({
  "type": z.literal("CUSTOM_MESSAGE"),
  "resetAt": z.number().nullable().optional(),
  "text": z.string(),
}), z.looseObject({
  "type": z.literal("IMAGE"),
  "resetAt": z.number().nullable().optional(),
  "text": z.string(),
})])
export type LcdMessage = z.infer<typeof lcdMessageSchema>

export const lcdMessageUnionSchema = z.looseObject({
  "type": z.enum(["LEAVE_PACKAGE_AT_DOOR", "DO_NOT_DISTURB", "CUSTOM_MESSAGE", "IMAGE"]).optional(),
  "resetAt": z.number().nullable().optional(),
  "text": z.string().optional(),
})
export type LcdMessageUnion = z.infer<typeof lcdMessageUnionSchema>

export const leakSettingsSchema = z.looseObject({
  "isInternalEnabled": z.boolean().optional(),
  "isExternalEnabled": z.boolean().optional(),
})
export type LeakSettings = z.infer<typeof leakSettingsSchema>

export const ledFloodLedSchema = z.boolean()
export type LedFloodLed = z.infer<typeof ledFloodLedSchema>

export const ledIsEnabledSchema = z.boolean()
export type LedIsEnabled = z.infer<typeof ledIsEnabledSchema>

export const ledWelcomeLedSchema = z.boolean()
export type LedWelcomeLed = z.infer<typeof ledWelcomeLedSchema>

export const lightDeviceSettingsSchema = z.looseObject({
  "isIndicatorEnabled": z.boolean().optional(),
  "pirDuration": z.number().min(0).optional(),
  "pirSensitivity": z.number().min(0).max(100).optional(),
  "ledLevel": z.number().min(1).max(6).optional(),
})
export type LightDeviceSettings = z.infer<typeof lightDeviceSettingsSchema>

export const lightIdSchema = z.string()
export type LightId = z.infer<typeof lightIdSchema>

export const lightModeSchema = z.union([z.literal("always"), z.literal("motion"), z.literal("off")])
export type LightMode = z.infer<typeof lightModeSchema>

export const lightModelKeySchema = z.literal("light")
export type LightModelKey = z.infer<typeof lightModelKeySchema>

export const lightSettingsSchema = z.looseObject({
  "isEnabled": z.boolean().optional(),
  "margin": z.number().optional(),
  "lowThreshold": z.number().min(1).max(503192).nullable().optional(),
  "highThreshold": z.number().nullable().optional(),
})
export type LightSettings = z.infer<typeof lightSettingsSchema>

export const linkStationIdSchema = z.string()
export type LinkStationId = z.infer<typeof linkStationIdSchema>

export const linkStationIsAlarmHubSchema = z.boolean()
export type LinkStationIsAlarmHub = z.infer<typeof linkStationIsAlarmHubSchema>

export const linkStationLastEventSchema = z.number().nullable()
export type LinkStationLastEvent = z.infer<typeof linkStationLastEventSchema>

export const linkStationLedIsEnabledSchema = z.boolean()
export type LinkStationLedIsEnabled = z.infer<typeof linkStationLedIsEnabledSchema>

export const linkstationModelKeySchema = z.literal("linkstation")
export type LinkstationModelKey = z.infer<typeof linkstationModelKeySchema>

export const liveviewIdSchema = z.string()
export type LiveviewId = z.infer<typeof liveviewIdSchema>

export const liveviewModelKeySchema = z.literal("liveview")
export type LiveviewModelKey = z.infer<typeof liveviewModelKeySchema>

export const macSchema = z.string()
export type Mac = z.infer<typeof macSchema>

export const micVolumeSchema = z.number().min(0).max(100)
export type MicVolume = z.infer<typeof micVolumeSchema>

export const motionSettingsSchema = z.looseObject({
  "isEnabled": z.boolean().optional(),
  "sensitivity": z.number().min(0).max(100).optional(),
  "sensitivityWhenArmed": z.number().min(0).max(100).optional(),
})
export type MotionSettings = z.infer<typeof motionSettingsSchema>

export const nameSchema = z.string()
export type Name = z.infer<typeof nameSchema>

export const nfcMetadataSchema = z.looseObject({
  "nfc": z.looseObject({
  "ulpId": z.string().nullable(),
}),
})
export type NfcMetadata = z.infer<typeof nfcMetadataSchema>

export const nvrArmModeSchema = z.looseObject({
  "status": z.enum(["arming", "armed", "breach", "disabled"]),
  "armProfileId": z.string().nullable().optional(),
  "armedAt": z.number().nullable(),
  "willBeArmedAt": z.number().nullable(),
  "breachDetectedAt": z.number().nullable(),
  "breachEventCount": z.number(),
  "breachTriggerEventId": z.string().nullable(),
  "breachEventId": z.string().nullable(),
})
export type NvrArmMode = z.infer<typeof nvrArmModeSchema>

export const nvrIdSchema = z.string()
export type NvrId = z.infer<typeof nvrIdSchema>

export const nvrModelKeySchema = z.literal("nvr")
export type NvrModelKey = z.infer<typeof nvrModelKeySchema>

export const objectTypesSchema = z.array(z.enum(["person", "vehicle", "package", "licensePlate", "face", "animal"]))
export type ObjectTypes = z.infer<typeof objectTypesSchema>

export const osdIsDateEnabledSchema = z.boolean()
export type OsdIsDateEnabled = z.infer<typeof osdIsDateEnabledSchema>

export const osdIsDebugEnabledSchema = z.boolean()
export type OsdIsDebugEnabled = z.infer<typeof osdIsDebugEnabledSchema>

export const osdIsLogoEnabledSchema = z.boolean()
export type OsdIsLogoEnabled = z.infer<typeof osdIsLogoEnabledSchema>

export const osdIsNameEnabledSchema = z.boolean()
export type OsdIsNameEnabled = z.infer<typeof osdIsNameEnabledSchema>

export const osdOverlayLocationSchema = z.enum(["topLeft", "topMiddle", "topRight", "bottomLeft", "bottomMiddle", "bottomRight"])
export type OsdOverlayLocation = z.infer<typeof osdOverlayLocationSchema>

export const protectVersionSchema = z.string()
export type ProtectVersion = z.infer<typeof protectVersionSchema>

export const recordEverythingSchema = z.boolean()
export type RecordEverything = z.infer<typeof recordEverythingSchema>

export const relayIdSchema = z.string()
export type RelayId = z.infer<typeof relayIdSchema>

export const relayInputActionOutputIdSchema = z.number().nullable()
export type RelayInputActionOutputId = z.infer<typeof relayInputActionOutputIdSchema>

export const relayInputActionTriggerSchema = z.enum(["switchedOn", "switchedOff"]).nullable()
export type RelayInputActionTrigger = z.infer<typeof relayInputActionTriggerSchema>

export const relayInputActionTypeSchema = z.enum(["setOutputOn", "setOutputOff", "toggleOutput", "followInput"]).nullable()
export type RelayInputActionType = z.infer<typeof relayInputActionTypeSchema>

export const relayInputIdSchema = z.number()
export type RelayInputId = z.infer<typeof relayInputIdSchema>

export const relayInputNameSchema = z.string().nullable()
export type RelayInputName = z.infer<typeof relayInputNameSchema>

export const relayInputStateSchema = z.enum(["on", "off"]).nullable()
export type RelayInputState = z.infer<typeof relayInputStateSchema>

export const relayLedIsEnabledSchema = z.boolean()
export type RelayLedIsEnabled = z.infer<typeof relayLedIsEnabledSchema>

export const relayModelKeySchema = z.literal("relay")
export type RelayModelKey = z.infer<typeof relayModelKeySchema>

export const relayOutputDelaySchema = z.number().nullable()
export type RelayOutputDelay = z.infer<typeof relayOutputDelaySchema>

export const relayOutputIdSchema = z.number()
export type RelayOutputId = z.infer<typeof relayOutputIdSchema>

export const relayOutputNameSchema = z.string().nullable()
export type RelayOutputName = z.infer<typeof relayOutputNameSchema>

export const relayOutputPulseDurationSchema = z.number().nullable()
export type RelayOutputPulseDuration = z.infer<typeof relayOutputPulseDurationSchema>

export const relayOutputRebootStateSchema = z.enum(["restore", "on", "off"])
export type RelayOutputRebootState = z.infer<typeof relayOutputRebootStateSchema>

export const relayOutputStateSchema = z.enum(["on", "off", "offOtp"]).nullable()
export type RelayOutputState = z.infer<typeof relayOutputStateSchema>

export const relayOutputTypeSchema = z.enum(["garageDoor", "gate", "valve", "siren", "custom"]).nullable()
export type RelayOutputType = z.infer<typeof relayOutputTypeSchema>

export const ringtoneIdSchema = z.string()
export type RingtoneId = z.infer<typeof ringtoneIdSchema>

export const sensorAlarmTriggeredAtSchema = z.number().nullable()
export type SensorAlarmTriggeredAt = z.infer<typeof sensorAlarmTriggeredAtSchema>

export const sensorArmProfileIdsSchema = z.array(z.string().max(64)).max(32).nullable()
export type SensorArmProfileIds = z.infer<typeof sensorArmProfileIdsSchema>

export const sensorExternalLeakDetectedAtSchema = z.number().nullable()
export type SensorExternalLeakDetectedAt = z.infer<typeof sensorExternalLeakDetectedAtSchema>

export const sensorHasCustomSensitivityWhenArmedSchema = z.boolean()
export type SensorHasCustomSensitivityWhenArmed = z.infer<typeof sensorHasCustomSensitivityWhenArmedSchema>

export const sensorIdSchema = z.string()
export type SensorId = z.infer<typeof sensorIdSchema>

export const sensorIsMotionDetectedSchema = z.boolean()
export type SensorIsMotionDetected = z.infer<typeof sensorIsMotionDetectedSchema>

export const sensorIsOpenedSchema = z.boolean().nullable()
export type SensorIsOpened = z.infer<typeof sensorIsOpenedSchema>

export const sensorLeakDetectedAtSchema = z.number().nullable()
export type SensorLeakDetectedAt = z.infer<typeof sensorLeakDetectedAtSchema>

export const sensorModelKeySchema = z.literal("sensor")
export type SensorModelKey = z.infer<typeof sensorModelKeySchema>

export const sensorMotionDetectedAtSchema = z.number().nullable()
export type SensorMotionDetectedAt = z.infer<typeof sensorMotionDetectedAtSchema>

export const sensorMountTypeSchema = z.enum(["door", "window", "garage", "leak", "none"])
export type SensorMountType = z.infer<typeof sensorMountTypeSchema>

export const sensorOpenStatusChangedAtSchema = z.number().nullable()
export type SensorOpenStatusChangedAt = z.infer<typeof sensorOpenStatusChangedAtSchema>

export const sensorScheduleModeSchema = z.enum(["always", "when_armed"])
export type SensorScheduleMode = z.infer<typeof sensorScheduleModeSchema>

export const sensorStatusSchema = z.enum(["neutral", "low", "safe", "high", "unknown"])
export type SensorStatus = z.infer<typeof sensorStatusSchema>

export const sensorValueSchema = z.number()
export type SensorValue = z.infer<typeof sensorValueSchema>

export const signalQualitySchema = z.number().nullable()
export type SignalQuality = z.infer<typeof signalQualitySchema>

export const signalStrengthSchema = z.number().nullable()
export type SignalStrength = z.infer<typeof signalStrengthSchema>

export const sirenConnectionTypeSchema = z.enum(["ucp4", "lora"])
export type SirenConnectionType = z.infer<typeof sirenConnectionTypeSchema>

export const sirenDurationSchema = z.union([z.literal(5000), z.literal(10000), z.literal(20000), z.literal(30000)])
export type SirenDuration = z.infer<typeof sirenDurationSchema>

export const sirenDurationSecondsSchema = z.union([z.literal(5), z.literal(10), z.literal(20), z.literal(30)])
export type SirenDurationSeconds = z.infer<typeof sirenDurationSecondsSchema>

export const sirenIdSchema = z.string()
export type SirenId = z.infer<typeof sirenIdSchema>

export const sirenLedIsEnabledSchema = z.boolean()
export type SirenLedIsEnabled = z.infer<typeof sirenLedIsEnabledSchema>

export const sirenModelKeySchema = z.literal("siren")
export type SirenModelKey = z.infer<typeof sirenModelKeySchema>

export const sirenStatusActivatedAtSchema = z.number().nullable()
export type SirenStatusActivatedAt = z.infer<typeof sirenStatusActivatedAtSchema>

export const sirenStatusIsActiveSchema = z.boolean()
export type SirenStatusIsActive = z.infer<typeof sirenStatusIsActiveSchema>

export const sirenVolumeSchema = z.number().int().min(1).max(100)
export type SirenVolume = z.infer<typeof sirenVolumeSchema>

export const snapshotChannelSchema = z.enum(["main", "package"])
export type SnapshotChannel = z.infer<typeof snapshotChannelSchema>

export const speakerFeatureFlagsHasMicSchema = z.boolean()
export type SpeakerFeatureFlagsHasMic = z.infer<typeof speakerFeatureFlagsHasMicSchema>

export const speakerIdSchema = z.string()
export type SpeakerId = z.infer<typeof speakerIdSchema>

export const speakerIsMicEnabledSchema = z.boolean()
export type SpeakerIsMicEnabled = z.infer<typeof speakerIsMicEnabledSchema>

export const speakerMicVolumeSchema = z.number().int().min(0).max(100)
export type SpeakerMicVolume = z.infer<typeof speakerMicVolumeSchema>

export const speakerModelKeySchema = z.literal("speaker")
export type SpeakerModelKey = z.infer<typeof speakerModelKeySchema>

export const speakerStateModeSchema = z.enum(["listen", "talk"])
export type SpeakerStateMode = z.infer<typeof speakerStateModeSchema>

export const speakerStateStatusSchema = z.enum(["idle", "streaming", "playing", "tts_playing", "uploading"])
export type SpeakerStateStatus = z.infer<typeof speakerStateStatusSchema>

export const speakerVolumeSchema = z.number().int().min(0).max(100)
export type SpeakerVolume = z.infer<typeof speakerVolumeSchema>

export const streamLimitSchema = z.number()
export type StreamLimit = z.infer<typeof streamLimitSchema>

export const talkbackStreamBitsPerSampleSchema = z.number().int().gt(0)
export type TalkbackStreamBitsPerSample = z.infer<typeof talkbackStreamBitsPerSampleSchema>

export const talkbackStreamCodecSchema = z.string()
export type TalkbackStreamCodec = z.infer<typeof talkbackStreamCodecSchema>

export const talkbackStreamSamplingRateSchema = z.number().int().gt(0)
export type TalkbackStreamSamplingRate = z.infer<typeof talkbackStreamSamplingRateSchema>

export const talkbackStreamUrlSchema = z.url()
export type TalkbackStreamUrl = z.infer<typeof talkbackStreamUrlSchema>

export const tamperingDetectedAtSchema = z.number().nullable()
export type TamperingDetectedAt = z.infer<typeof tamperingDetectedAtSchema>

export const temperatureSettingsSchema = z.looseObject({
  "isEnabled": z.boolean().optional(),
  "margin": z.number().optional(),
  "lowThreshold": z.number().min(-39).max(124).nullable().optional(),
  "highThreshold": z.number().nullable().optional(),
})
export type TemperatureSettings = z.infer<typeof temperatureSettingsSchema>

export const ulpUserIdSchema = z.string()
export type UlpUserId = z.infer<typeof ulpUserIdSchema>

export const ulpUserModelKeySchema = z.literal("ulpUser")
export type UlpUserModelKey = z.infer<typeof ulpUserModelKeySchema>

export const updatedAtSchema = z.number()
export type UpdatedAt = z.infer<typeof updatedAtSchema>

export const userIdSchema = z.string()
export type UserId = z.infer<typeof userIdSchema>

export const userModelKeySchema = z.literal("user")
export type UserModelKey = z.infer<typeof userModelKeySchema>

export const videoModeSchema = z.enum(["default", "highFps", "sport", "slowShutter", "lprReflex", "lprNoneReflex"])
export type VideoMode = z.infer<typeof videoModeSchema>

export const viewerIdSchema = z.string()
export type ViewerId = z.infer<typeof viewerIdSchema>

export const viewerModelKeySchema = z.literal("viewer")
export type ViewerModelKey = z.infer<typeof viewerModelKeySchema>

export const wirelessBatteryIsLowSchema = z.boolean()
export type WirelessBatteryIsLow = z.infer<typeof wirelessBatteryIsLowSchema>

export const wirelessBatteryPercentageSchema = z.number().nullable()
export type WirelessBatteryPercentage = z.infer<typeof wirelessBatteryPercentageSchema>

export const aiPortSchema = z.looseObject({
  "id": deviceIdSchema,
  "modelKey": aiportModelKeySchema,
  "state": deviceStateSchema,
  "name": z.union([nameSchema, z.null()]),
  "mac": macSchema,
})
export type AiPort = z.infer<typeof aiPortSchema>

export const aiPortPartialWithReferenceSchema = z.looseObject({
  "id": deviceIdSchema,
  "modelKey": aiportModelKeySchema,
  "state": deviceStateSchema.optional(),
  "name": z.union([nameSchema, z.null()]).optional(),
  "mac": macSchema.optional(),
})
export type AiPortPartialWithReference = z.infer<typeof aiPortPartialWithReferenceSchema>

export const aiPortReferenceSchema = z.looseObject({
  "id": deviceIdSchema,
  "modelKey": aiportModelKeySchema,
})
export type AiPortReference = z.infer<typeof aiPortReferenceSchema>

export const aiProcessorSchema = z.looseObject({
  "id": deviceIdSchema,
  "modelKey": aiprocessorModelKeySchema,
  "state": deviceStateSchema,
  "name": z.union([nameSchema, z.null()]),
  "mac": macSchema,
})
export type AiProcessor = z.infer<typeof aiProcessorSchema>

export const aiProcessorPartialWithReferenceSchema = z.looseObject({
  "id": deviceIdSchema,
  "modelKey": aiprocessorModelKeySchema,
  "state": deviceStateSchema.optional(),
  "name": z.union([nameSchema, z.null()]).optional(),
  "mac": macSchema.optional(),
})
export type AiProcessorPartialWithReference = z.infer<typeof aiProcessorPartialWithReferenceSchema>

export const aiProcessorReferenceSchema = z.looseObject({
  "id": deviceIdSchema,
  "modelKey": aiprocessorModelKeySchema,
})
export type AiProcessorReference = z.infer<typeof aiProcessorReferenceSchema>

export const alarmHubBatteryConnectedEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("alarmHubBatteryConnected"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
})
export type AlarmHubBatteryConnectedEvent = z.infer<typeof alarmHubBatteryConnectedEventSchema>

export const alarmHubBatteryLowEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("alarmHubBatteryLow"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
})
export type AlarmHubBatteryLowEvent = z.infer<typeof alarmHubBatteryLowEventSchema>

export const alarmHubButtonPressEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("alarmHubButtonPress"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
  "metadata": z.looseObject({
  "pin": z.looseObject({
  "text": z.string(),
}),
  "status": z.looseObject({
  "text": z.string(),
}),
  "button": z.looseObject({
  "text": z.enum(["function", "alarmHubButton", "arm", "disarm", "night", "panic", "left", "right", "input1", "input2"]),
}),
  "alarmType": z.looseObject({
  "text": z.enum(["smoke", "CO", "glassBreak", "sensorButtonPress", "tamper", "short", "cut"]),
}),
  "deviceId": z.looseObject({
  "text": z.string(),
}),
  "deviceName": z.looseObject({
  "text": z.string(),
}),
}).optional(),
})
export type AlarmHubButtonPressEvent = z.infer<typeof alarmHubButtonPressEventSchema>

export const alarmHubEntryClosedEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("alarmHubEntryClosed"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
  "metadata": z.looseObject({
  "pin": z.looseObject({
  "text": z.string(),
}),
  "status": z.looseObject({
  "text": z.string(),
}),
  "deviceId": z.looseObject({
  "text": z.string(),
}),
  "deviceName": z.looseObject({
  "text": z.string(),
}),
}).optional(),
})
export type AlarmHubEntryClosedEvent = z.infer<typeof alarmHubEntryClosedEventSchema>

export const alarmHubEntryOpenedEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("alarmHubEntryOpened"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
  "metadata": z.looseObject({
  "pin": z.looseObject({
  "text": z.string(),
}),
  "status": z.looseObject({
  "text": z.string(),
}),
  "deviceId": z.looseObject({
  "text": z.string(),
}),
  "deviceName": z.looseObject({
  "text": z.string(),
}),
}).optional(),
})
export type AlarmHubEntryOpenedEvent = z.infer<typeof alarmHubEntryOpenedEventSchema>

export const alarmHubGlassBreakEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("alarmHubGlassBreak"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
  "metadata": z.looseObject({
  "pin": z.looseObject({
  "text": z.string(),
}),
  "status": z.looseObject({
  "text": z.string(),
}),
  "alarmType": z.looseObject({
  "text": z.enum(["smoke", "CO", "glassBreak", "sensorButtonPress", "tamper", "short", "cut"]),
}),
  "deviceId": z.looseObject({
  "text": z.string(),
}),
  "deviceName": z.looseObject({
  "text": z.string(),
}),
}).optional(),
})
export type AlarmHubGlassBreakEvent = z.infer<typeof alarmHubGlassBreakEventSchema>

export const alarmHubMotionEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("alarmHubMotion"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
  "metadata": z.looseObject({
  "pin": z.looseObject({
  "text": z.string(),
}),
  "status": z.looseObject({
  "text": z.string(),
}),
  "deviceId": z.looseObject({
  "text": z.string(),
}),
  "deviceName": z.looseObject({
  "text": z.string(),
}),
}).optional(),
})
export type AlarmHubMotionEvent = z.infer<typeof alarmHubMotionEventSchema>

export const alarmHubRelaySwitchedEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("alarmHubRelaySwitched"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
})
export type AlarmHubRelaySwitchedEvent = z.infer<typeof alarmHubRelaySwitchedEventSchema>

export const alarmHubSmokeEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("alarmHubSmoke"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
  "metadata": z.looseObject({
  "pin": z.looseObject({
  "text": z.string(),
}),
  "status": z.looseObject({
  "text": z.string(),
}),
  "alarmType": z.looseObject({
  "text": z.enum(["smoke", "CO", "glassBreak", "sensorButtonPress", "tamper", "short", "cut"]),
}),
  "deviceId": z.looseObject({
  "text": z.string(),
}),
  "deviceName": z.looseObject({
  "text": z.string(),
}),
}).optional(),
})
export type AlarmHubSmokeEvent = z.infer<typeof alarmHubSmokeEventSchema>

export const alarmHubTamperEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("alarmHubTamper"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
  "metadata": z.looseObject({
  "pin": z.looseObject({
  "text": z.string(),
}),
  "status": z.looseObject({
  "text": z.string(),
}),
  "alarmType": z.looseObject({
  "text": z.enum(["smoke", "CO", "glassBreak", "sensorButtonPress", "tamper", "short", "cut"]),
}),
  "deviceId": z.looseObject({
  "text": z.string(),
}),
  "deviceName": z.looseObject({
  "text": z.string(),
}),
}).optional(),
})
export type AlarmHubTamperEvent = z.infer<typeof alarmHubTamperEventSchema>

export const armScheduleSchema = z.looseObject({
  "start": armScheduleStartSchema,
  "end": armScheduleEndSchema,
})
export type ArmSchedule = z.infer<typeof armScheduleSchema>

export const automationsSchema = z.array(automationIdSchema)
export type Automations = z.infer<typeof automationsSchema>

export const bridgeSchema = z.looseObject({
  "id": bridgeIdSchema,
  "modelKey": bridgeModelKeySchema,
  "state": deviceStateSchema,
  "name": z.union([nameSchema, z.null()]),
  "mac": macSchema,
  "platform": bridgePlatformSchema,
  "clients": bridgeClientsSchema,
  "maxClients": bridgeMaxClientsSchema,
})
export type Bridge = z.infer<typeof bridgeSchema>

export const bridgePartialWithReferenceSchema = z.looseObject({
  "id": bridgeIdSchema,
  "modelKey": bridgeModelKeySchema,
  "state": deviceStateSchema.optional(),
  "name": z.union([nameSchema, z.null()]).optional(),
  "mac": macSchema.optional(),
  "platform": bridgePlatformSchema.optional(),
  "clients": bridgeClientsSchema.optional(),
  "maxClients": bridgeMaxClientsSchema.optional(),
})
export type BridgePartialWithReference = z.infer<typeof bridgePartialWithReferenceSchema>

export const bridgeReferenceSchema = z.looseObject({
  "id": bridgeIdSchema,
  "modelKey": bridgeModelKeySchema,
})
export type BridgeReference = z.infer<typeof bridgeReferenceSchema>

export const cameraMotionEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("motion"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
})
export type CameraMotionEvent = z.infer<typeof cameraMotionEventSchema>

export const cameraReferenceSchema = z.looseObject({
  "id": cameraIdSchema,
  "modelKey": cameraModelKeySchema,
})
export type CameraReference = z.infer<typeof cameraReferenceSchema>

export const cameraSmartDetectAudioEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("smartAudioDetect"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
  "smartDetectTypes": z.array(z.enum(["alrmSmoke", "alrmCmonx", "alrmSiren", "alrmBabyCry", "alrmSpeak", "alrmBark", "alrmBurglar", "alrmCarHorn", "alrmGlassBreak"])).nullable(),
})
export type CameraSmartDetectAudioEvent = z.infer<typeof cameraSmartDetectAudioEventSchema>

export const cameraSmartDetectLineEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("smartDetectLine"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
  "smartDetectTypes": z.array(z.enum(["person", "vehicle", "package", "licensePlate", "face", "animal"])).nullable(),
})
export type CameraSmartDetectLineEvent = z.infer<typeof cameraSmartDetectLineEventSchema>

export const cameraSmartDetectLoiterEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("smartDetectLoiterZone"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
  "smartDetectTypes": z.array(z.enum(["person", "vehicle", "package", "licensePlate", "face", "animal"])).nullable(),
})
export type CameraSmartDetectLoiterEvent = z.infer<typeof cameraSmartDetectLoiterEventSchema>

export const cameraSmartDetectZoneEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("smartDetectZone"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
  "smartDetectTypes": z.array(z.enum(["person", "vehicle", "package", "licensePlate", "face", "animal"])).nullable(),
})
export type CameraSmartDetectZoneEvent = z.infer<typeof cameraSmartDetectZoneEventSchema>

export const chimeReferenceSchema = z.looseObject({
  "id": chimeIdSchema,
  "modelKey": chimeModelKeySchema,
})
export type ChimeReference = z.infer<typeof chimeReferenceSchema>

export const createdQualitiesSchema = z.array(channelQualitySchema).min(1)
export type CreatedQualities = z.infer<typeof createdQualitiesSchema>

export const deviceBulkReferenceSchema = z.union([z.looseObject({
  "id": z.union([nvrIdSchema, z.array(nvrIdSchema)]),
  "modelKey": nvrModelKeySchema,
}), z.looseObject({
  "id": z.union([cameraIdSchema, z.array(cameraIdSchema)]),
  "modelKey": cameraModelKeySchema,
}), z.looseObject({
  "id": z.union([chimeIdSchema, z.array(chimeIdSchema)]),
  "modelKey": chimeModelKeySchema,
}), z.looseObject({
  "id": z.union([lightIdSchema, z.array(lightIdSchema)]),
  "modelKey": lightModelKeySchema,
}), z.looseObject({
  "id": z.union([viewerIdSchema, z.array(viewerIdSchema)]),
  "modelKey": viewerModelKeySchema,
}), z.looseObject({
  "id": z.union([speakerIdSchema, z.array(speakerIdSchema)]),
  "modelKey": speakerModelKeySchema,
}), z.looseObject({
  "id": z.union([bridgeIdSchema, z.array(bridgeIdSchema)]),
  "modelKey": bridgeModelKeySchema,
}), z.looseObject({
  "id": z.union([sensorIdSchema, z.array(sensorIdSchema)]),
  "modelKey": sensorModelKeySchema,
}), z.looseObject({
  "id": z.union([sirenIdSchema, z.array(sirenIdSchema)]),
  "modelKey": sirenModelKeySchema,
}), z.looseObject({
  "id": z.union([fobIdSchema, z.array(fobIdSchema)]),
  "modelKey": fobModelKeySchema,
}), z.looseObject({
  "id": z.union([relayIdSchema, z.array(relayIdSchema)]),
  "modelKey": relayModelKeySchema,
}), z.looseObject({
  "id": z.union([deviceIdSchema, z.array(deviceIdSchema)]),
  "modelKey": aiprocessorModelKeySchema,
}), z.looseObject({
  "id": z.union([deviceIdSchema, z.array(deviceIdSchema)]),
  "modelKey": aiportModelKeySchema,
}), z.looseObject({
  "id": z.union([linkStationIdSchema, z.array(linkStationIdSchema)]),
  "modelKey": linkstationModelKeySchema,
})])
export type DeviceBulkReference = z.infer<typeof deviceBulkReferenceSchema>

export const fileSchemaSchema = z.looseObject({
  "name": fileNameSchema,
  "type": assetFileTypeSchema,
  "originalName": fileOriginalNameSchema.optional(),
  "path": filePathSchema,
})
export type FileSchema = z.infer<typeof fileSchemaSchema>

export const fingerprintIdentifiedEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("fingerprintIdentified"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
  "metadata": fingerprintMetadataSchema,
})
export type FingerprintIdentifiedEvent = z.infer<typeof fingerprintIdentifiedEventSchema>

export const fobFeatureFlagsSchema = z.looseObject({
  "buttons": fobButtonsSchema,
})
export type FobFeatureFlags = z.infer<typeof fobFeatureFlagsSchema>

export const fobReferenceSchema = z.looseObject({
  "id": fobIdSchema,
  "modelKey": fobModelKeySchema,
})
export type FobReference = z.infer<typeof fobReferenceSchema>

export const ledSettingsSchema = z.looseObject({
  "isEnabled": ledIsEnabledSchema,
  "welcomeLed": ledWelcomeLedSchema,
  "floodLed": ledFloodLedSchema,
})
export type LedSettings = z.infer<typeof ledSettingsSchema>

export const lightModeSettingsSchema = z.looseObject({
  "mode": lightModeSchema.optional(),
  "enableAt": enableAtSchema.optional(),
})
export type LightModeSettings = z.infer<typeof lightModeSettingsSchema>

export const lightMotionEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("lightMotion"),
  "start": z.number().gt(0),
  "device": deviceIdSchema,
})
export type LightMotionEvent = z.infer<typeof lightMotionEventSchema>

export const lightReferenceSchema = z.looseObject({
  "id": lightIdSchema,
  "modelKey": lightModelKeySchema,
})
export type LightReference = z.infer<typeof lightReferenceSchema>

export const linkStationLedSettingsSchema = z.looseObject({
  "isEnabled": linkStationLedIsEnabledSchema,
})
export type LinkStationLedSettings = z.infer<typeof linkStationLedSettingsSchema>

export const linkStationReferenceSchema = z.looseObject({
  "id": linkStationIdSchema,
  "modelKey": linkstationModelKeySchema,
})
export type LinkStationReference = z.infer<typeof linkStationReferenceSchema>

export const liveviewSchema = z.looseObject({
  "id": liveviewIdSchema,
  "modelKey": liveviewModelKeySchema,
  "name": z.string(),
  "isDefault": z.boolean(),
  "isGlobal": z.boolean(),
  "owner": userIdSchema,
  "layout": z.number().min(1).max(26),
  "slots": z.array(z.looseObject({
  "cameras": z.array(cameraIdSchema),
  "cycleMode": z.enum(["motion", "time"]),
  "cycleInterval": z.number(),
})),
})
export type Liveview = z.infer<typeof liveviewSchema>

export const nfcCardScannedEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("nfcCardScanned"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
  "metadata": nfcMetadataSchema,
})
export type NfcCardScannedEvent = z.infer<typeof nfcCardScannedEventSchema>

export const nvrSchema = z.looseObject({
  "id": nvrIdSchema,
  "modelKey": nvrModelKeySchema,
  "name": z.union([nameSchema, z.null()]),
  "doorbellSettings": doorbellSettingsSchema,
  "armMode": nvrArmModeSchema,
})
export type Nvr = z.infer<typeof nvrSchema>

export const nvrPartialWithReferenceSchema = z.looseObject({
  "id": nvrIdSchema,
  "modelKey": nvrModelKeySchema,
  "name": z.union([nameSchema, z.null()]).optional(),
  "doorbellSettings": doorbellSettingsSchema.optional(),
  "armMode": nvrArmModeSchema.optional(),
})
export type NvrPartialWithReference = z.infer<typeof nvrPartialWithReferenceSchema>

export const nvrReferenceSchema = z.looseObject({
  "id": nvrIdSchema,
  "modelKey": nvrModelKeySchema,
})
export type NvrReference = z.infer<typeof nvrReferenceSchema>

export const osdSettingsSchema = z.looseObject({
  "isNameEnabled": osdIsNameEnabledSchema,
  "isDateEnabled": osdIsDateEnabledSchema,
  "isLogoEnabled": osdIsLogoEnabledSchema,
  "isDebugEnabled": osdIsDebugEnabledSchema,
  "overlayLocation": osdOverlayLocationSchema,
})
export type OsdSettings = z.infer<typeof osdSettingsSchema>

export const relayInputSchema = z.looseObject({
  "id": relayInputIdSchema,
  "name": relayInputNameSchema,
  "state": relayInputStateSchema,
  "actionTrigger": relayInputActionTriggerSchema,
  "actionType": relayInputActionTypeSchema,
  "actionOutputId": relayInputActionOutputIdSchema,
})
export type RelayInput = z.infer<typeof relayInputSchema>

export const relayInputChangedEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("relayInputChanged"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
  "metadata": z.looseObject({
  "inputState": z.looseObject({
  "text": z.enum(["circuitClosed", "circuitOpen"]),
}),
  "inputChannel": z.looseObject({
  "text": z.string(),
}),
}),
})
export type RelayInputChangedEvent = z.infer<typeof relayInputChangedEventSchema>

export const relayLedSettingsSchema = z.looseObject({
  "isEnabled": relayLedIsEnabledSchema,
})
export type RelayLedSettings = z.infer<typeof relayLedSettingsSchema>

export const relayOutputSchema = z.looseObject({
  "id": relayOutputIdSchema,
  "name": relayOutputNameSchema,
  "type": relayOutputTypeSchema,
  "delay": relayOutputDelaySchema,
  "pulseDuration": relayOutputPulseDurationSchema,
  "state": relayOutputStateSchema,
  "rebootState": relayOutputRebootStateSchema,
})
export type RelayOutput = z.infer<typeof relayOutputSchema>

export const relayReferenceSchema = z.looseObject({
  "id": relayIdSchema,
  "modelKey": relayModelKeySchema,
})
export type RelayReference = z.infer<typeof relayReferenceSchema>

export const removedQualitiesSchema = z.union([z.array(channelQualitySchema).min(1), channelQualitySchema])
export type RemovedQualities = z.infer<typeof removedQualitiesSchema>

export const ringEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("ring"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
})
export type RingEvent = z.infer<typeof ringEventSchema>

export const ringSettingsSchema = z.looseObject({
  "cameraId": cameraIdSchema,
  "repeatTimes": z.number().min(1).max(10),
  "ringtoneId": ringtoneIdSchema.optional(),
  "volume": z.number().min(0).max(100),
})
export type RingSettings = z.infer<typeof ringSettingsSchema>

export const sensorAlarmEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("sensorAlarm"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
  "metadata": z.looseObject({
  "alarmType": z.looseObject({
  "text": z.enum(["smoke", "CO", "glassBreak", "sensorButtonPress", "tamper", "short", "cut"]),
}),
}),
})
export type SensorAlarmEvent = z.infer<typeof sensorAlarmEventSchema>

export const sensorBatteryLowEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("sensorBatteryLow"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
  "metadata": z.looseObject({
  "sensorBatteryPercentage": z.looseObject({
  "number": z.number(),
}),
}),
})
export type SensorBatteryLowEvent = z.infer<typeof sensorBatteryLowEventSchema>

export const sensorButtonPressedEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("sensorButtonPressed"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
  "metadata": z.looseObject({
  "button": z.looseObject({
  "text": z.enum(["function", "alarmHubButton", "arm", "disarm", "night", "panic", "left", "right", "input1", "input2"]),
}),
}),
})
export type SensorButtonPressedEvent = z.infer<typeof sensorButtonPressedEventSchema>

export const sensorClosedEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("sensorClosed"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
  "metadata": z.looseObject({
  "sensorMountType": z.looseObject({
  "text": sensorMountTypeSchema,
}),
}),
})
export type SensorClosedEvent = z.infer<typeof sensorClosedEventSchema>

export const sensorCoFaultEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("sensorCoFault"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
})
export type SensorCoFaultEvent = z.infer<typeof sensorCoFaultEventSchema>

export const sensorExtremeValueEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("sensorExtremeValues"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
  "metadata": z.looseObject({
  "sensorType": z.looseObject({
  "text": z.enum(["temperature", "light", "humidity", "aqi", "vape", "tvoc", "pm1p0", "pm2p5", "pm4p0", "pm10p0", "co2", "voc"]),
}),
  "sensorValue": z.looseObject({
  "text": sensorValueSchema,
}),
  "status": z.looseObject({
  "text": sensorStatusSchema,
}),
}),
})
export type SensorExtremeValueEvent = z.infer<typeof sensorExtremeValueEventSchema>

export const sensorMotionEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("sensorMotion"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
})
export type SensorMotionEvent = z.infer<typeof sensorMotionEventSchema>

export const sensorOpenEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("sensorOpened"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
  "metadata": z.looseObject({
  "sensorMountType": z.looseObject({
  "text": sensorMountTypeSchema,
}),
}),
})
export type SensorOpenEvent = z.infer<typeof sensorOpenEventSchema>

export const sensorReferenceSchema = z.looseObject({
  "id": sensorIdSchema,
  "modelKey": sensorModelKeySchema,
})
export type SensorReference = z.infer<typeof sensorReferenceSchema>

export const sensorSmokeBatteryLowEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("sensorSmokeBatteryLow"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
})
export type SensorSmokeBatteryLowEvent = z.infer<typeof sensorSmokeBatteryLowEventSchema>

export const sensorSmokeEndOfLifeEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("sensorSmokeEndOfLife"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
})
export type SensorSmokeEndOfLifeEvent = z.infer<typeof sensorSmokeEndOfLifeEventSchema>

export const sensorSmokeFaultEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("sensorSmokeFault"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
})
export type SensorSmokeFaultEvent = z.infer<typeof sensorSmokeFaultEventSchema>

export const sensorSmokeNeedsCleaningEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("sensorSmokeNeedsCleaning"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
})
export type SensorSmokeNeedsCleaningEvent = z.infer<typeof sensorSmokeNeedsCleaningEventSchema>

export const sensorSmokeTestEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("sensorSmokeTest"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
  "metadata": z.looseObject({
  "source": z.enum(["remote", "local"]).optional(),
}),
})
export type SensorSmokeTestEvent = z.infer<typeof sensorSmokeTestEventSchema>

export const sensorStatsSchema = z.looseObject({
  "light": z.looseObject({
  "value": z.union([sensorValueSchema, z.null()]).optional(),
  "status": sensorStatusSchema.optional(),
}).optional(),
  "humidity": z.looseObject({
  "value": z.union([sensorValueSchema, z.null()]).optional(),
  "status": sensorStatusSchema.optional(),
}).optional(),
  "temperature": z.looseObject({
  "value": z.union([sensorValueSchema, z.null()]).optional(),
  "status": sensorStatusSchema.optional(),
}).optional(),
})
export type SensorStats = z.infer<typeof sensorStatsSchema>

export const sensorTamperEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("sensorTamper"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
})
export type SensorTamperEvent = z.infer<typeof sensorTamperEventSchema>

export const sensorVapeEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("sensorVape"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
})
export type SensorVapeEvent = z.infer<typeof sensorVapeEventSchema>

export const sensorWaterLeakEventSchema = z.looseObject({
  "id": eventIdSchema,
  "modelKey": eventModelKeySchema,
  "type": z.literal("sensorWaterLeak"),
  "start": z.number().gt(0),
  "end": z.number().nullable().optional(),
  "device": deviceIdSchema,
  "metadata": z.looseObject({
  "sensorMountType": z.looseObject({
  "text": sensorMountTypeSchema,
}),
}),
})
export type SensorWaterLeakEvent = z.infer<typeof sensorWaterLeakEventSchema>

export const signalStateSchema = z.looseObject({
  "signalQuality": signalQualitySchema,
  "signalStrength": signalStrengthSchema,
})
export type SignalState = z.infer<typeof signalStateSchema>

export const sirenLedSettingsExternalSchema = z.looseObject({
  "isEnabled": sirenLedIsEnabledSchema,
})
export type SirenLedSettingsExternal = z.infer<typeof sirenLedSettingsExternalSchema>

export const sirenReferenceSchema = z.looseObject({
  "id": sirenIdSchema,
  "modelKey": sirenModelKeySchema,
})
export type SirenReference = z.infer<typeof sirenReferenceSchema>

export const sirenStatusDurationSchema = z.union([sirenDurationSchema, z.null()])
export type SirenStatusDuration = z.infer<typeof sirenStatusDurationSchema>

export const smartDetectSettingsSchema = z.looseObject({
  "objectTypes": objectTypesSchema,
  "audioTypes": audioTypesSchema,
})
export type SmartDetectSettings = z.infer<typeof smartDetectSettingsSchema>

export const speakerFeatureFlagsSchema = z.looseObject({
  "hasMic": speakerFeatureFlagsHasMicSchema,
})
export type SpeakerFeatureFlags = z.infer<typeof speakerFeatureFlagsSchema>

export const speakerReferenceSchema = z.looseObject({
  "id": speakerIdSchema,
  "modelKey": speakerModelKeySchema,
})
export type SpeakerReference = z.infer<typeof speakerReferenceSchema>

export const speakerStateSchema = z.looseObject({
  "status": speakerStateStatusSchema,
  "mode": speakerStateModeSchema,
})
export type SpeakerState = z.infer<typeof speakerStateSchema>

export const talkbackSessionSchema = z.looseObject({
  "url": talkbackStreamUrlSchema,
  "codec": talkbackStreamCodecSchema,
  "samplingRate": talkbackStreamSamplingRateSchema,
  "bitsPerSample": talkbackStreamBitsPerSampleSchema,
})
export type TalkbackSession = z.infer<typeof talkbackSessionSchema>

export const ulpUserSchema = z.looseObject({
  "id": ulpUserIdSchema,
  "firstName": z.string(),
  "lastName": z.string(),
  "fullName": z.string(),
  "status": z.enum(["ACTIVE", "DEACTIVATED"]),
  "modelKey": ulpUserModelKeySchema,
})
export type UlpUser = z.infer<typeof ulpUserSchema>

export const userSchema = z.looseObject({
  "id": userIdSchema,
  "name": z.string(),
  "firstName": z.string().nullable(),
  "lastName": z.string().nullable(),
  "email": z.string().nullable(),
  "ucoreUserId": z.string().nullable(),
  "modelKey": userModelKeySchema,
})
export type User = z.infer<typeof userSchema>

export const viewerSchema = z.looseObject({
  "id": viewerIdSchema,
  "modelKey": viewerModelKeySchema,
  "state": deviceStateSchema,
  "name": z.union([nameSchema, z.null()]),
  "mac": macSchema,
  "liveview": z.union([liveviewIdSchema, z.null()]),
  "streamLimit": streamLimitSchema,
})
export type Viewer = z.infer<typeof viewerSchema>

export const viewerPartialWithReferenceSchema = z.looseObject({
  "id": viewerIdSchema,
  "modelKey": viewerModelKeySchema,
  "state": deviceStateSchema.optional(),
  "name": z.union([nameSchema, z.null()]).optional(),
  "mac": macSchema.optional(),
  "liveview": z.union([liveviewIdSchema, z.null()]).optional(),
  "streamLimit": streamLimitSchema.optional(),
})
export type ViewerPartialWithReference = z.infer<typeof viewerPartialWithReferenceSchema>

export const viewerReferenceSchema = z.looseObject({
  "id": viewerIdSchema,
  "modelKey": viewerModelKeySchema,
})
export type ViewerReference = z.infer<typeof viewerReferenceSchema>

export const wirelessBatteryStatusSchema = z.looseObject({
  "percentage": wirelessBatteryPercentageSchema,
  "isLow": wirelessBatteryIsLowSchema,
})
export type WirelessBatteryStatus = z.infer<typeof wirelessBatteryStatusSchema>

export const wirelessBridgeIdSchema = z.union([bridgeIdSchema, z.null()])
export type WirelessBridgeId = z.infer<typeof wirelessBridgeIdSchema>

export const cameraSchema = z.looseObject({
  "id": cameraIdSchema,
  "modelKey": cameraModelKeySchema,
  "state": deviceStateSchema,
  "name": z.union([nameSchema, z.null()]),
  "mac": macSchema,
  "isMicEnabled": isMicEnabledSchema,
  "osdSettings": osdSettingsSchema,
  "ledSettings": ledSettingsSchema,
  "lcdMessage": lcdMessageUnionSchema,
  "micVolume": micVolumeSchema,
  "activePatrolSlot": z.union([activePatrolSlotSchema, z.null()]),
  "videoMode": videoModeSchema,
  "hdrType": hdrTypeSchema,
  "featureFlags": cameraFeatureFlagsSchema,
  "smartDetectSettings": smartDetectSettingsSchema,
  "hasPackageCamera": hasPackageCameraSchema,
})
export type Camera = z.infer<typeof cameraSchema>

export const cameraPartialWithReferenceSchema = z.looseObject({
  "id": cameraIdSchema,
  "modelKey": cameraModelKeySchema,
  "state": deviceStateSchema.optional(),
  "name": z.union([nameSchema, z.null()]).optional(),
  "mac": macSchema.optional(),
  "isMicEnabled": isMicEnabledSchema.optional(),
  "osdSettings": osdSettingsSchema.optional(),
  "ledSettings": ledSettingsSchema.optional(),
  "lcdMessage": lcdMessageUnionSchema.optional(),
  "micVolume": micVolumeSchema.optional(),
  "activePatrolSlot": z.union([activePatrolSlotSchema, z.null()]).optional(),
  "videoMode": videoModeSchema.optional(),
  "hdrType": hdrTypeSchema.optional(),
  "featureFlags": cameraFeatureFlagsSchema.optional(),
  "smartDetectSettings": smartDetectSettingsSchema.optional(),
  "hasPackageCamera": hasPackageCameraSchema.optional(),
})
export type CameraPartialWithReference = z.infer<typeof cameraPartialWithReferenceSchema>

export const chimeSchema = z.looseObject({
  "id": chimeIdSchema,
  "modelKey": chimeModelKeySchema,
  "state": deviceStateSchema,
  "name": z.union([nameSchema, z.null()]),
  "mac": macSchema,
  "cameraIds": z.array(cameraIdSchema),
  "ringSettings": z.array(ringSettingsSchema),
})
export type Chime = z.infer<typeof chimeSchema>

export const chimePartialWithReferenceSchema = z.looseObject({
  "id": chimeIdSchema,
  "modelKey": chimeModelKeySchema,
  "state": deviceStateSchema.optional(),
  "name": z.union([nameSchema, z.null()]).optional(),
  "mac": macSchema.optional(),
  "cameraIds": z.array(cameraIdSchema).optional(),
  "ringSettings": z.array(ringSettingsSchema).optional(),
})
export type ChimePartialWithReference = z.infer<typeof chimePartialWithReferenceSchema>

export const deviceReferenceSchema = z.discriminatedUnion("modelKey", [nvrReferenceSchema, cameraReferenceSchema, chimeReferenceSchema, lightReferenceSchema, viewerReferenceSchema, speakerReferenceSchema, bridgeReferenceSchema, sensorReferenceSchema, sirenReferenceSchema, fobReferenceSchema, relayReferenceSchema, aiProcessorReferenceSchema, aiPortReferenceSchema, linkStationReferenceSchema])
export type DeviceReference = z.infer<typeof deviceReferenceSchema>

export const devicesBulkRemoveSchema = z.looseObject({
  "type": z.literal("remove"),
  "item": deviceBulkReferenceSchema,
})
export type DevicesBulkRemove = z.infer<typeof devicesBulkRemoveSchema>

export const eventSchema = z.discriminatedUnion("type", [ringEventSchema, sensorExtremeValueEventSchema, sensorWaterLeakEventSchema, sensorTamperEventSchema, sensorBatteryLowEventSchema, sensorAlarmEventSchema, sensorVapeEventSchema, sensorOpenEventSchema, sensorClosedEventSchema, sensorSmokeTestEventSchema, sensorSmokeBatteryLowEventSchema, sensorSmokeNeedsCleaningEventSchema, sensorSmokeFaultEventSchema, sensorCoFaultEventSchema, sensorSmokeEndOfLifeEventSchema, sensorMotionEventSchema, sensorButtonPressedEventSchema, lightMotionEventSchema, cameraMotionEventSchema, cameraSmartDetectAudioEventSchema, cameraSmartDetectZoneEventSchema, cameraSmartDetectLineEventSchema, cameraSmartDetectLoiterEventSchema, relayInputChangedEventSchema, alarmHubMotionEventSchema, alarmHubEntryOpenedEventSchema, alarmHubEntryClosedEventSchema, alarmHubSmokeEventSchema, alarmHubGlassBreakEventSchema, alarmHubButtonPressEventSchema, alarmHubTamperEventSchema, alarmHubRelaySwitchedEventSchema, alarmHubBatteryLowEventSchema, alarmHubBatteryConnectedEventSchema, nfcCardScannedEventSchema, fingerprintIdentifiedEventSchema])
export type Event = z.infer<typeof eventSchema>

export const lightSchema = z.looseObject({
  "id": lightIdSchema,
  "modelKey": lightModelKeySchema,
  "state": deviceStateSchema,
  "name": z.union([nameSchema, z.null()]),
  "mac": macSchema,
  "lightModeSettings": lightModeSettingsSchema,
  "lightDeviceSettings": lightDeviceSettingsSchema,
  "isDark": isDarkSchema,
  "isLightOn": isLightOnSchema,
  "isLightForceEnabled": isLightForceEnabledSchema,
  "lastMotion": lastMotionSchema,
  "isPirMotionDetected": isPirMotionDetectedSchema,
  "camera": z.union([cameraIdSchema, z.null()]),
})
export type Light = z.infer<typeof lightSchema>

export const lightPartialWithReferenceSchema = z.looseObject({
  "id": lightIdSchema,
  "modelKey": lightModelKeySchema,
  "state": deviceStateSchema.optional(),
  "name": z.union([nameSchema, z.null()]).optional(),
  "mac": macSchema.optional(),
  "lightModeSettings": lightModeSettingsSchema.optional(),
  "lightDeviceSettings": lightDeviceSettingsSchema.optional(),
  "isDark": isDarkSchema.optional(),
  "isLightOn": isLightOnSchema.optional(),
  "isLightForceEnabled": isLightForceEnabledSchema.optional(),
  "lastMotion": lastMotionSchema.optional(),
  "isPirMotionDetected": isPirMotionDetectedSchema.optional(),
  "camera": z.union([cameraIdSchema, z.null()]).optional(),
})
export type LightPartialWithReference = z.infer<typeof lightPartialWithReferenceSchema>

export const linkStationSchema = z.looseObject({
  "id": linkStationIdSchema,
  "modelKey": linkstationModelKeySchema,
  "state": deviceStateSchema,
  "name": z.union([nameSchema, z.null()]),
  "mac": macSchema,
  "isAlarmHub": linkStationIsAlarmHubSchema,
  "ledSettings": linkStationLedSettingsSchema,
  "lastEvent": linkStationLastEventSchema,
  "alarmHub": alarmHubStatusSchema.optional(),
})
export type LinkStation = z.infer<typeof linkStationSchema>

export const linkStationPartialWithReferenceSchema = z.looseObject({
  "id": linkStationIdSchema,
  "modelKey": linkstationModelKeySchema,
  "state": deviceStateSchema.optional(),
  "name": z.union([nameSchema, z.null()]).optional(),
  "mac": macSchema.optional(),
  "isAlarmHub": linkStationIsAlarmHubSchema.optional(),
  "ledSettings": linkStationLedSettingsSchema.optional(),
  "lastEvent": linkStationLastEventSchema.optional(),
  "alarmHub": alarmHubStatusSchema.optional(),
})
export type LinkStationPartialWithReference = z.infer<typeof linkStationPartialWithReferenceSchema>

export const relayInputsSchema = z.array(relayInputSchema)
export type RelayInputs = z.infer<typeof relayInputsSchema>

export const relayOutputsSchema = z.array(relayOutputSchema)
export type RelayOutputs = z.infer<typeof relayOutputsSchema>

export const schedulesSchema = z.array(armScheduleSchema)
export type Schedules = z.infer<typeof schedulesSchema>

export const sirenStatusSchema = z.looseObject({
  "isActive": sirenStatusIsActiveSchema,
  "activatedAt": sirenStatusActivatedAtSchema,
  "duration": sirenStatusDurationSchema,
})
export type SirenStatus = z.infer<typeof sirenStatusSchema>

export const speakerSchema = z.looseObject({
  "id": speakerIdSchema,
  "modelKey": speakerModelKeySchema,
  "state": deviceStateSchema,
  "name": z.union([nameSchema, z.null()]),
  "mac": macSchema,
  "volume": speakerVolumeSchema,
  "micVolume": speakerMicVolumeSchema,
  "isMicEnabled": speakerIsMicEnabledSchema,
  "speakerState": speakerStateSchema,
  "featureFlags": speakerFeatureFlagsSchema,
})
export type Speaker = z.infer<typeof speakerSchema>

export const speakerPartialWithReferenceSchema = z.looseObject({
  "id": speakerIdSchema,
  "modelKey": speakerModelKeySchema,
  "state": deviceStateSchema.optional(),
  "name": z.union([nameSchema, z.null()]).optional(),
  "mac": macSchema.optional(),
  "volume": speakerVolumeSchema.optional(),
  "micVolume": speakerMicVolumeSchema.optional(),
  "isMicEnabled": speakerIsMicEnabledSchema.optional(),
  "speakerState": speakerStateSchema.optional(),
  "featureFlags": speakerFeatureFlagsSchema.optional(),
})
export type SpeakerPartialWithReference = z.infer<typeof speakerPartialWithReferenceSchema>

export const wirelessConnectionStateSchema = z.looseObject({
  "signalState": signalStateSchema,
  "batteryStatus": wirelessBatteryStatusSchema,
  "bridge": wirelessBridgeIdSchema,
})
export type WirelessConnectionState = z.infer<typeof wirelessConnectionStateSchema>

export const armProfileSchema = z.looseObject({
  "id": armProfileIdSchema,
  "name": armProfileNameSchema,
  "automations": automationsSchema,
  "creator": z.union([userIdSchema, z.null()]),
  "schedules": schedulesSchema,
  "recordEverything": recordEverythingSchema,
  "activationDelay": activationDelaySchema,
  "createdAt": createdAtSchema,
  "updatedAt": updatedAtSchema,
})
export type ArmProfile = z.infer<typeof armProfileSchema>

export const deviceBulkSchema = z.union([z.looseObject({
  "id": z.union([nvrIdSchema, z.array(nvrIdSchema)]),
  "modelKey": nvrModelKeySchema,
  "name": z.union([nameSchema, z.null()]),
  "doorbellSettings": doorbellSettingsSchema,
  "armMode": nvrArmModeSchema,
}), z.looseObject({
  "id": z.union([cameraIdSchema, z.array(cameraIdSchema)]),
  "modelKey": cameraModelKeySchema,
  "state": deviceStateSchema,
  "name": z.union([nameSchema, z.null()]),
  "mac": macSchema,
  "isMicEnabled": isMicEnabledSchema,
  "osdSettings": osdSettingsSchema,
  "ledSettings": ledSettingsSchema,
  "lcdMessage": lcdMessageUnionSchema,
  "micVolume": micVolumeSchema,
  "activePatrolSlot": z.union([activePatrolSlotSchema, z.null()]),
  "videoMode": videoModeSchema,
  "hdrType": hdrTypeSchema,
  "featureFlags": cameraFeatureFlagsSchema,
  "smartDetectSettings": smartDetectSettingsSchema,
  "hasPackageCamera": hasPackageCameraSchema,
}), z.looseObject({
  "id": z.union([chimeIdSchema, z.array(chimeIdSchema)]),
  "modelKey": chimeModelKeySchema,
  "state": deviceStateSchema,
  "name": z.union([nameSchema, z.null()]),
  "mac": macSchema,
  "cameraIds": z.array(cameraIdSchema),
  "ringSettings": z.array(ringSettingsSchema),
}), z.looseObject({
  "id": z.union([lightIdSchema, z.array(lightIdSchema)]),
  "modelKey": lightModelKeySchema,
  "state": deviceStateSchema,
  "name": z.union([nameSchema, z.null()]),
  "mac": macSchema,
  "lightModeSettings": lightModeSettingsSchema,
  "lightDeviceSettings": lightDeviceSettingsSchema,
  "isDark": isDarkSchema,
  "isLightOn": isLightOnSchema,
  "isLightForceEnabled": isLightForceEnabledSchema,
  "lastMotion": lastMotionSchema,
  "isPirMotionDetected": isPirMotionDetectedSchema,
  "camera": z.union([cameraIdSchema, z.null()]),
}), z.looseObject({
  "id": z.union([viewerIdSchema, z.array(viewerIdSchema)]),
  "modelKey": viewerModelKeySchema,
  "state": deviceStateSchema,
  "name": z.union([nameSchema, z.null()]),
  "mac": macSchema,
  "liveview": z.union([liveviewIdSchema, z.null()]),
  "streamLimit": streamLimitSchema,
}), z.looseObject({
  "id": z.union([speakerIdSchema, z.array(speakerIdSchema)]),
  "modelKey": speakerModelKeySchema,
  "state": deviceStateSchema,
  "name": z.union([nameSchema, z.null()]),
  "mac": macSchema,
  "volume": speakerVolumeSchema,
  "micVolume": speakerMicVolumeSchema,
  "isMicEnabled": speakerIsMicEnabledSchema,
  "speakerState": speakerStateSchema,
  "featureFlags": speakerFeatureFlagsSchema,
}), z.looseObject({
  "id": z.union([bridgeIdSchema, z.array(bridgeIdSchema)]),
  "modelKey": bridgeModelKeySchema,
  "state": deviceStateSchema,
  "name": z.union([nameSchema, z.null()]),
  "mac": macSchema,
  "platform": bridgePlatformSchema,
  "clients": bridgeClientsSchema,
  "maxClients": bridgeMaxClientsSchema,
}), z.looseObject({
  "id": z.union([sensorIdSchema, z.array(sensorIdSchema)]),
  "modelKey": sensorModelKeySchema,
  "state": deviceStateSchema,
  "name": z.union([nameSchema, z.null()]),
  "mac": macSchema,
  "mountType": sensorMountTypeSchema,
  "batteryStatus": batteryStatusSchema,
  "stats": sensorStatsSchema,
  "lightSettings": lightSettingsSchema,
  "humiditySettings": humiditySettingsSchema,
  "temperatureSettings": temperatureSettingsSchema,
  "isOpened": sensorIsOpenedSchema,
  "openStatusChangedAt": sensorOpenStatusChangedAtSchema,
  "isMotionDetected": sensorIsMotionDetectedSchema,
  "motionDetectedAt": sensorMotionDetectedAtSchema,
  "motionSettings": motionSettingsSchema,
  "glassBreakSettings": glassBreakSettingsSchema,
  "scheduleMode": sensorScheduleModeSchema,
  "armProfileIds": sensorArmProfileIdsSchema,
  "hasCustomSensitivityWhenArmed": sensorHasCustomSensitivityWhenArmedSchema,
  "alarmTriggeredAt": sensorAlarmTriggeredAtSchema,
  "alarmSettings": alarmSettingsSchema,
  "leakDetectedAt": sensorLeakDetectedAtSchema,
  "externalLeakDetectedAt": sensorExternalLeakDetectedAtSchema,
  "leakSettings": leakSettingsSchema,
  "tamperingDetectedAt": tamperingDetectedAtSchema,
  "wirelessConnectionState": wirelessConnectionStateSchema,
}), z.looseObject({
  "id": z.union([sirenIdSchema, z.array(sirenIdSchema)]),
  "modelKey": sirenModelKeySchema,
  "state": deviceStateSchema,
  "name": z.union([nameSchema, z.null()]),
  "mac": macSchema,
  "volume": sirenVolumeSchema,
  "ledSettings": sirenLedSettingsExternalSchema,
  "sirenStatus": sirenStatusSchema,
  "connectionType": sirenConnectionTypeSchema,
  "wirelessConnectionState": wirelessConnectionStateSchema,
}), z.looseObject({
  "id": z.union([fobIdSchema, z.array(fobIdSchema)]),
  "modelKey": fobModelKeySchema,
  "state": deviceStateSchema,
  "name": z.union([nameSchema, z.null()]),
  "mac": macSchema,
  "awayState": fobAwayStateSchema,
  "buttonLabels": fobButtonLabelsSchema,
  "featureFlags": fobFeatureFlagsSchema,
  "wirelessConnectionState": wirelessConnectionStateSchema,
}), z.looseObject({
  "id": z.union([relayIdSchema, z.array(relayIdSchema)]),
  "modelKey": relayModelKeySchema,
  "state": deviceStateSchema,
  "name": z.union([nameSchema, z.null()]),
  "mac": macSchema,
  "ledSettings": relayLedSettingsSchema,
  "outputs": relayOutputsSchema,
  "inputs": relayInputsSchema,
  "wirelessConnectionState": wirelessConnectionStateSchema,
}), z.looseObject({
  "id": z.union([deviceIdSchema, z.array(deviceIdSchema)]),
  "modelKey": aiprocessorModelKeySchema,
  "state": deviceStateSchema,
  "name": z.union([nameSchema, z.null()]),
  "mac": macSchema,
}), z.looseObject({
  "id": z.union([deviceIdSchema, z.array(deviceIdSchema)]),
  "modelKey": aiportModelKeySchema,
  "state": deviceStateSchema,
  "name": z.union([nameSchema, z.null()]),
  "mac": macSchema,
}), z.looseObject({
  "id": z.union([linkStationIdSchema, z.array(linkStationIdSchema)]),
  "modelKey": linkstationModelKeySchema,
  "state": deviceStateSchema,
  "name": z.union([nameSchema, z.null()]),
  "mac": macSchema,
  "isAlarmHub": linkStationIsAlarmHubSchema,
  "ledSettings": linkStationLedSettingsSchema,
  "lastEvent": linkStationLastEventSchema,
  "alarmHub": alarmHubStatusSchema.optional(),
})])
export type DeviceBulk = z.infer<typeof deviceBulkSchema>

export const deviceBulkPartialWithReferenceSchema = z.union([z.looseObject({
  "id": z.union([nvrIdSchema, z.array(nvrIdSchema)]),
  "modelKey": nvrModelKeySchema,
  "name": z.union([nameSchema, z.null()]).optional(),
  "doorbellSettings": doorbellSettingsSchema.optional(),
  "armMode": nvrArmModeSchema.optional(),
}), z.looseObject({
  "id": z.union([cameraIdSchema, z.array(cameraIdSchema)]),
  "modelKey": cameraModelKeySchema,
  "state": deviceStateSchema.optional(),
  "name": z.union([nameSchema, z.null()]).optional(),
  "mac": macSchema.optional(),
  "isMicEnabled": isMicEnabledSchema.optional(),
  "osdSettings": osdSettingsSchema.optional(),
  "ledSettings": ledSettingsSchema.optional(),
  "lcdMessage": lcdMessageUnionSchema.optional(),
  "micVolume": micVolumeSchema.optional(),
  "activePatrolSlot": z.union([activePatrolSlotSchema, z.null()]).optional(),
  "videoMode": videoModeSchema.optional(),
  "hdrType": hdrTypeSchema.optional(),
  "featureFlags": cameraFeatureFlagsSchema.optional(),
  "smartDetectSettings": smartDetectSettingsSchema.optional(),
  "hasPackageCamera": hasPackageCameraSchema.optional(),
}), z.looseObject({
  "id": z.union([chimeIdSchema, z.array(chimeIdSchema)]),
  "modelKey": chimeModelKeySchema,
  "state": deviceStateSchema.optional(),
  "name": z.union([nameSchema, z.null()]).optional(),
  "mac": macSchema.optional(),
  "cameraIds": z.array(cameraIdSchema).optional(),
  "ringSettings": z.array(ringSettingsSchema).optional(),
}), z.looseObject({
  "id": z.union([lightIdSchema, z.array(lightIdSchema)]),
  "modelKey": lightModelKeySchema,
  "state": deviceStateSchema.optional(),
  "name": z.union([nameSchema, z.null()]).optional(),
  "mac": macSchema.optional(),
  "lightModeSettings": lightModeSettingsSchema.optional(),
  "lightDeviceSettings": lightDeviceSettingsSchema.optional(),
  "isDark": isDarkSchema.optional(),
  "isLightOn": isLightOnSchema.optional(),
  "isLightForceEnabled": isLightForceEnabledSchema.optional(),
  "lastMotion": lastMotionSchema.optional(),
  "isPirMotionDetected": isPirMotionDetectedSchema.optional(),
  "camera": z.union([cameraIdSchema, z.null()]).optional(),
}), z.looseObject({
  "id": z.union([viewerIdSchema, z.array(viewerIdSchema)]),
  "modelKey": viewerModelKeySchema,
  "state": deviceStateSchema.optional(),
  "name": z.union([nameSchema, z.null()]).optional(),
  "mac": macSchema.optional(),
  "liveview": z.union([liveviewIdSchema, z.null()]).optional(),
  "streamLimit": streamLimitSchema.optional(),
}), z.looseObject({
  "id": z.union([speakerIdSchema, z.array(speakerIdSchema)]),
  "modelKey": speakerModelKeySchema,
  "state": deviceStateSchema.optional(),
  "name": z.union([nameSchema, z.null()]).optional(),
  "mac": macSchema.optional(),
  "volume": speakerVolumeSchema.optional(),
  "micVolume": speakerMicVolumeSchema.optional(),
  "isMicEnabled": speakerIsMicEnabledSchema.optional(),
  "speakerState": speakerStateSchema.optional(),
  "featureFlags": speakerFeatureFlagsSchema.optional(),
}), z.looseObject({
  "id": z.union([bridgeIdSchema, z.array(bridgeIdSchema)]),
  "modelKey": bridgeModelKeySchema,
  "state": deviceStateSchema.optional(),
  "name": z.union([nameSchema, z.null()]).optional(),
  "mac": macSchema.optional(),
  "platform": bridgePlatformSchema.optional(),
  "clients": bridgeClientsSchema.optional(),
  "maxClients": bridgeMaxClientsSchema.optional(),
}), z.looseObject({
  "id": z.union([sensorIdSchema, z.array(sensorIdSchema)]),
  "modelKey": sensorModelKeySchema,
  "state": deviceStateSchema.optional(),
  "name": z.union([nameSchema, z.null()]).optional(),
  "mac": macSchema.optional(),
  "mountType": sensorMountTypeSchema.optional(),
  "batteryStatus": batteryStatusSchema.optional(),
  "stats": sensorStatsSchema.optional(),
  "lightSettings": lightSettingsSchema.optional(),
  "humiditySettings": humiditySettingsSchema.optional(),
  "temperatureSettings": temperatureSettingsSchema.optional(),
  "isOpened": sensorIsOpenedSchema.optional(),
  "openStatusChangedAt": sensorOpenStatusChangedAtSchema.optional(),
  "isMotionDetected": sensorIsMotionDetectedSchema.optional(),
  "motionDetectedAt": sensorMotionDetectedAtSchema.optional(),
  "motionSettings": motionSettingsSchema.optional(),
  "glassBreakSettings": glassBreakSettingsSchema.optional(),
  "scheduleMode": sensorScheduleModeSchema.optional(),
  "armProfileIds": sensorArmProfileIdsSchema.optional(),
  "hasCustomSensitivityWhenArmed": sensorHasCustomSensitivityWhenArmedSchema.optional(),
  "alarmTriggeredAt": sensorAlarmTriggeredAtSchema.optional(),
  "alarmSettings": alarmSettingsSchema.optional(),
  "leakDetectedAt": sensorLeakDetectedAtSchema.optional(),
  "externalLeakDetectedAt": sensorExternalLeakDetectedAtSchema.optional(),
  "leakSettings": leakSettingsSchema.optional(),
  "tamperingDetectedAt": tamperingDetectedAtSchema.optional(),
  "wirelessConnectionState": wirelessConnectionStateSchema.optional(),
}), z.looseObject({
  "id": z.union([sirenIdSchema, z.array(sirenIdSchema)]),
  "modelKey": sirenModelKeySchema,
  "state": deviceStateSchema.optional(),
  "name": z.union([nameSchema, z.null()]).optional(),
  "mac": macSchema.optional(),
  "volume": sirenVolumeSchema.optional(),
  "ledSettings": sirenLedSettingsExternalSchema.optional(),
  "sirenStatus": sirenStatusSchema.optional(),
  "connectionType": sirenConnectionTypeSchema.optional(),
  "wirelessConnectionState": wirelessConnectionStateSchema.optional(),
}), z.looseObject({
  "id": z.union([fobIdSchema, z.array(fobIdSchema)]),
  "modelKey": fobModelKeySchema,
  "state": deviceStateSchema.optional(),
  "name": z.union([nameSchema, z.null()]).optional(),
  "mac": macSchema.optional(),
  "awayState": fobAwayStateSchema.optional(),
  "buttonLabels": fobButtonLabelsSchema.optional(),
  "featureFlags": fobFeatureFlagsSchema.optional(),
  "wirelessConnectionState": wirelessConnectionStateSchema.optional(),
}), z.looseObject({
  "id": z.union([relayIdSchema, z.array(relayIdSchema)]),
  "modelKey": relayModelKeySchema,
  "state": deviceStateSchema.optional(),
  "name": z.union([nameSchema, z.null()]).optional(),
  "mac": macSchema.optional(),
  "ledSettings": relayLedSettingsSchema.optional(),
  "outputs": relayOutputsSchema.optional(),
  "inputs": relayInputsSchema.optional(),
  "wirelessConnectionState": wirelessConnectionStateSchema.optional(),
}), z.looseObject({
  "id": z.union([deviceIdSchema, z.array(deviceIdSchema)]),
  "modelKey": aiprocessorModelKeySchema,
  "state": deviceStateSchema.optional(),
  "name": z.union([nameSchema, z.null()]).optional(),
  "mac": macSchema.optional(),
}), z.looseObject({
  "id": z.union([deviceIdSchema, z.array(deviceIdSchema)]),
  "modelKey": aiportModelKeySchema,
  "state": deviceStateSchema.optional(),
  "name": z.union([nameSchema, z.null()]).optional(),
  "mac": macSchema.optional(),
}), z.looseObject({
  "id": z.union([linkStationIdSchema, z.array(linkStationIdSchema)]),
  "modelKey": linkstationModelKeySchema,
  "state": deviceStateSchema.optional(),
  "name": z.union([nameSchema, z.null()]).optional(),
  "mac": macSchema.optional(),
  "isAlarmHub": linkStationIsAlarmHubSchema.optional(),
  "ledSettings": linkStationLedSettingsSchema.optional(),
  "lastEvent": linkStationLastEventSchema.optional(),
  "alarmHub": alarmHubStatusSchema.optional(),
})])
export type DeviceBulkPartialWithReference = z.infer<typeof deviceBulkPartialWithReferenceSchema>

export const deviceRemoveSchema = z.looseObject({
  "type": z.literal("remove"),
  "item": deviceReferenceSchema,
})
export type DeviceRemove = z.infer<typeof deviceRemoveSchema>

export const eventAddSchema = z.looseObject({
  "type": z.literal("add"),
  "item": eventSchema,
})
export type EventAdd = z.infer<typeof eventAddSchema>

export const eventUpdateSchema = z.looseObject({
  "type": z.literal("update"),
  "item": eventSchema,
})
export type EventUpdate = z.infer<typeof eventUpdateSchema>

export const fobSchema = z.looseObject({
  "id": fobIdSchema,
  "modelKey": fobModelKeySchema,
  "state": deviceStateSchema,
  "name": z.union([nameSchema, z.null()]),
  "mac": macSchema,
  "awayState": fobAwayStateSchema,
  "buttonLabels": fobButtonLabelsSchema,
  "featureFlags": fobFeatureFlagsSchema,
  "wirelessConnectionState": wirelessConnectionStateSchema,
})
export type Fob = z.infer<typeof fobSchema>

export const fobPartialWithReferenceSchema = z.looseObject({
  "id": fobIdSchema,
  "modelKey": fobModelKeySchema,
  "state": deviceStateSchema.optional(),
  "name": z.union([nameSchema, z.null()]).optional(),
  "mac": macSchema.optional(),
  "awayState": fobAwayStateSchema.optional(),
  "buttonLabels": fobButtonLabelsSchema.optional(),
  "featureFlags": fobFeatureFlagsSchema.optional(),
  "wirelessConnectionState": wirelessConnectionStateSchema.optional(),
})
export type FobPartialWithReference = z.infer<typeof fobPartialWithReferenceSchema>

export const relaySchema = z.looseObject({
  "id": relayIdSchema,
  "modelKey": relayModelKeySchema,
  "state": deviceStateSchema,
  "name": z.union([nameSchema, z.null()]),
  "mac": macSchema,
  "ledSettings": relayLedSettingsSchema,
  "outputs": relayOutputsSchema,
  "inputs": relayInputsSchema,
  "wirelessConnectionState": wirelessConnectionStateSchema,
})
export type Relay = z.infer<typeof relaySchema>

export const relayPartialWithReferenceSchema = z.looseObject({
  "id": relayIdSchema,
  "modelKey": relayModelKeySchema,
  "state": deviceStateSchema.optional(),
  "name": z.union([nameSchema, z.null()]).optional(),
  "mac": macSchema.optional(),
  "ledSettings": relayLedSettingsSchema.optional(),
  "outputs": relayOutputsSchema.optional(),
  "inputs": relayInputsSchema.optional(),
  "wirelessConnectionState": wirelessConnectionStateSchema.optional(),
})
export type RelayPartialWithReference = z.infer<typeof relayPartialWithReferenceSchema>

export const sensorSchema = z.looseObject({
  "id": sensorIdSchema,
  "modelKey": sensorModelKeySchema,
  "state": deviceStateSchema,
  "name": z.union([nameSchema, z.null()]),
  "mac": macSchema,
  "mountType": sensorMountTypeSchema,
  "batteryStatus": batteryStatusSchema,
  "stats": sensorStatsSchema,
  "lightSettings": lightSettingsSchema,
  "humiditySettings": humiditySettingsSchema,
  "temperatureSettings": temperatureSettingsSchema,
  "isOpened": sensorIsOpenedSchema,
  "openStatusChangedAt": sensorOpenStatusChangedAtSchema,
  "isMotionDetected": sensorIsMotionDetectedSchema,
  "motionDetectedAt": sensorMotionDetectedAtSchema,
  "motionSettings": motionSettingsSchema,
  "glassBreakSettings": glassBreakSettingsSchema,
  "scheduleMode": sensorScheduleModeSchema,
  "armProfileIds": sensorArmProfileIdsSchema,
  "hasCustomSensitivityWhenArmed": sensorHasCustomSensitivityWhenArmedSchema,
  "alarmTriggeredAt": sensorAlarmTriggeredAtSchema,
  "alarmSettings": alarmSettingsSchema,
  "leakDetectedAt": sensorLeakDetectedAtSchema,
  "externalLeakDetectedAt": sensorExternalLeakDetectedAtSchema,
  "leakSettings": leakSettingsSchema,
  "tamperingDetectedAt": tamperingDetectedAtSchema,
  "wirelessConnectionState": wirelessConnectionStateSchema,
})
export type Sensor = z.infer<typeof sensorSchema>

export const sensorPartialWithReferenceSchema = z.looseObject({
  "id": sensorIdSchema,
  "modelKey": sensorModelKeySchema,
  "state": deviceStateSchema.optional(),
  "name": z.union([nameSchema, z.null()]).optional(),
  "mac": macSchema.optional(),
  "mountType": sensorMountTypeSchema.optional(),
  "batteryStatus": batteryStatusSchema.optional(),
  "stats": sensorStatsSchema.optional(),
  "lightSettings": lightSettingsSchema.optional(),
  "humiditySettings": humiditySettingsSchema.optional(),
  "temperatureSettings": temperatureSettingsSchema.optional(),
  "isOpened": sensorIsOpenedSchema.optional(),
  "openStatusChangedAt": sensorOpenStatusChangedAtSchema.optional(),
  "isMotionDetected": sensorIsMotionDetectedSchema.optional(),
  "motionDetectedAt": sensorMotionDetectedAtSchema.optional(),
  "motionSettings": motionSettingsSchema.optional(),
  "glassBreakSettings": glassBreakSettingsSchema.optional(),
  "scheduleMode": sensorScheduleModeSchema.optional(),
  "armProfileIds": sensorArmProfileIdsSchema.optional(),
  "hasCustomSensitivityWhenArmed": sensorHasCustomSensitivityWhenArmedSchema.optional(),
  "alarmTriggeredAt": sensorAlarmTriggeredAtSchema.optional(),
  "alarmSettings": alarmSettingsSchema.optional(),
  "leakDetectedAt": sensorLeakDetectedAtSchema.optional(),
  "externalLeakDetectedAt": sensorExternalLeakDetectedAtSchema.optional(),
  "leakSettings": leakSettingsSchema.optional(),
  "tamperingDetectedAt": tamperingDetectedAtSchema.optional(),
  "wirelessConnectionState": wirelessConnectionStateSchema.optional(),
})
export type SensorPartialWithReference = z.infer<typeof sensorPartialWithReferenceSchema>

export const sirenSchema = z.looseObject({
  "id": sirenIdSchema,
  "modelKey": sirenModelKeySchema,
  "state": deviceStateSchema,
  "name": z.union([nameSchema, z.null()]),
  "mac": macSchema,
  "volume": sirenVolumeSchema,
  "ledSettings": sirenLedSettingsExternalSchema,
  "sirenStatus": sirenStatusSchema,
  "connectionType": sirenConnectionTypeSchema,
  "wirelessConnectionState": wirelessConnectionStateSchema,
})
export type Siren = z.infer<typeof sirenSchema>

export const sirenPartialWithReferenceSchema = z.looseObject({
  "id": sirenIdSchema,
  "modelKey": sirenModelKeySchema,
  "state": deviceStateSchema.optional(),
  "name": z.union([nameSchema, z.null()]).optional(),
  "mac": macSchema.optional(),
  "volume": sirenVolumeSchema.optional(),
  "ledSettings": sirenLedSettingsExternalSchema.optional(),
  "sirenStatus": sirenStatusSchema.optional(),
  "connectionType": sirenConnectionTypeSchema.optional(),
  "wirelessConnectionState": wirelessConnectionStateSchema.optional(),
})
export type SirenPartialWithReference = z.infer<typeof sirenPartialWithReferenceSchema>

export const deviceSchema = z.discriminatedUnion("modelKey", [nvrSchema, cameraSchema, chimeSchema, lightSchema, viewerSchema, speakerSchema, bridgeSchema, sensorSchema, sirenSchema, fobSchema, relaySchema, aiProcessorSchema, aiPortSchema, linkStationSchema])
export type Device = z.infer<typeof deviceSchema>

export const devicePartialWithReferenceSchema = z.discriminatedUnion("modelKey", [nvrPartialWithReferenceSchema, cameraPartialWithReferenceSchema, chimePartialWithReferenceSchema, lightPartialWithReferenceSchema, viewerPartialWithReferenceSchema, speakerPartialWithReferenceSchema, bridgePartialWithReferenceSchema, sensorPartialWithReferenceSchema, sirenPartialWithReferenceSchema, fobPartialWithReferenceSchema, relayPartialWithReferenceSchema, aiProcessorPartialWithReferenceSchema, aiPortPartialWithReferenceSchema, linkStationPartialWithReferenceSchema])
export type DevicePartialWithReference = z.infer<typeof devicePartialWithReferenceSchema>

export const devicesAddSchema = z.looseObject({
  "type": z.literal("add"),
  "item": deviceBulkSchema,
})
export type DevicesAdd = z.infer<typeof devicesAddSchema>

export const devicesBulkUpdateSchema = z.looseObject({
  "type": z.literal("update"),
  "item": deviceBulkPartialWithReferenceSchema,
})
export type DevicesBulkUpdate = z.infer<typeof devicesBulkUpdateSchema>

export const deviceAddSchema = z.looseObject({
  "type": z.literal("add"),
  "item": deviceSchema,
})
export type DeviceAdd = z.infer<typeof deviceAddSchema>

export const deviceUpdateSchema = z.looseObject({
  "type": z.literal("update"),
  "item": devicePartialWithReferenceSchema,
})
export type DeviceUpdate = z.infer<typeof deviceUpdateSchema>

export const deviceEventSchema = z.union([z.discriminatedUnion("type", [deviceAddSchema, deviceUpdateSchema, deviceRemoveSchema]), z.discriminatedUnion("type", [devicesAddSchema, devicesBulkUpdateSchema, devicesBulkRemoveSchema])])
export type DeviceEvent = z.infer<typeof deviceEventSchema>
